import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 16-ก.พ.-2564 08:31:04 ก่อนเที่ยง'
'File path: C:\\Users\\AdviceKpS\\Downloads\\Alumni Test Case 1.side'
'Generated by: 614259035@webmail.npru.ac.th'
'----------------------------------------------------'

String baseUrl = "https://tzs-global.com"

WebUI.openBrowser('')

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | /alumni-1/ |  | "
selenium.open("/alumni-1/")

"setWindowSize | 1936x1056 |  | "
// Method setWindowSize is not supported

"click | linkText=ลงทะเบียน |  | "
selenium.click("linkText=ลงทะเบียน")

"click | name=mr |  | "
selenium.click("name=mr")

"click | name=mr |  | "
selenium.click("name=mr")

"click | name=fname |  | "
selenium.click("name=fname")

"type | name=fname | ธนกฤต ตินพ | "
selenium.type("name=fname", "ธนกฤต ตินพ")

"click | name=mre |  | "
selenium.click("name=mre")

"click | name=mre |  | "
selenium.click("name=mre")

"click | name=ename |  | "
selenium.click("name=ename")

"type | name=ename | Thanakit Tinop | "
selenium.type("name=ename", "Thanakit Tinop")

"click | name=id |  | "
selenium.click("name=id")

"type | name=id | 1709700233733 | "
selenium.type("name=id", "1709700233733")

"click | name=date |  | "
selenium.click("name=date")

"type | name=date | 0002-02-07 | "
selenium.type("name=date", "0002-02-07")

"type | name=date | 0025-02-07 | "
selenium.type("name=date", "0025-02-07")

"type | name=date | 0256-02-07 | "
selenium.type("name=date", "0256-02-07")

"type | name=date | 2563-02-07 | "
selenium.type("name=date", "2563-02-07")

"type | name=date |  | "
selenium.type("name=date", "")

"type | name=date | 0002-02-07 | "
selenium.type("name=date", "0002-02-07")

"type | name=date | 0025-02-07 | "
selenium.type("name=date", "0025-02-07")

"type | name=date | 0254-02-07 | "
selenium.type("name=date", "0254-02-07")

"type | name=date | 2543-02-07 | "
selenium.type("name=date", "2543-02-07")

"click | name=job |  | "
selenium.click("name=job")

"type | name=job | - | "
selenium.type("name=job", "-")

"click | name=nation |  | "
selenium.click("name=nation")

"type | name=nation | ไทย | "
selenium.type("name=nation", "ไทย")

"click | name=nation2 |  | "
selenium.click("name=nation2")

"type | name=nation2 | ไทย | "
selenium.type("name=nation2", "ไทย")

"type | name=re | พุทธ | "
selenium.type("name=re", "พุทธ")

"type | name=blood | A | "
selenium.type("name=blood", "A")

"type | name=email | thanakittinop05@hotmail.com | "
selenium.type("name=email", "thanakittinop05@hotmail.com")

"type | name=tel | 0659216799 | "
selenium.type("name=tel", "0659216799")

"type | name=face | Thanakit Tinop | "
selenium.type("name=face", "Thanakit Tinop")

"type | name=line | thanakit | "
selenium.type("name=line", "thanakit")

"type | name=homea | 81 | "
selenium.type("name=homea", "81")

"type | name=mou | 4 | "
selenium.type("name=mou", "4")

"type | name=song | - | "
selenium.type("name=song", "-")

"type | name=road | - | "
selenium.type("name=road", "-")

"type | name=tampon | mjk=6,r] | "
selenium.type("name=tampon", "mjk=6,r]")

"click | name=tampon |  | "
selenium.click("name=tampon")

"click | css=.form-row:nth-child(11) |  | "
selenium.click("css=.form-row:nth-child(11)")

"doubleClick | css=.form-row:nth-child(11) |  | "
selenium.doubleClick("css=.form-row:nth-child(11)")

"type | name=tampon | ท่าชุมพล | "
selenium.type("name=tampon", "ท่าชุมพล")

"type | name=ampor | โพธาราม | "
selenium.type("name=ampor", "โพธาราม")

"type | name=prov | ราชบุรี | "
selenium.type("name=prov", "ราชบุรี")

"type | name=zipcode | 70120 | "
selenium.type("name=zipcode", "70120")

"type | name=h2 | 81 | "
selenium.type("name=h2", "81")

"type | name=m2 | 4 | "
selenium.type("name=m2", "4")

"type | name=s2 | - | "
selenium.type("name=s2", "-")

"type | name=road2 | - | "
selenium.type("name=road2", "-")

"type | name=t2 | ท่าชุมพล | "
selenium.type("name=t2", "ท่าชุมพล")

"type | name=a2 | โพธาราม | "
selenium.type("name=a2", "โพธาราม")

"type | name=prov2 | ราชบุรี | "
selenium.type("name=prov2", "ราชบุรี")

"type | name=zip2 | 70120 | "
selenium.type("name=zip2", "70120")

"type | name=phone | 0659216799 | "
selenium.type("name=phone", "0659216799")

"type | name=sid | 614259034 | "
selenium.type("name=sid", "614259034")

"type | name=sec | 61/47 | "
selenium.type("name=sec", "61/47")

"type | name=grade | 4.00 | "
selenium.type("name=grade", "4.00")

"type | name=ry | 2560 | "
selenium.type("name=ry", "2560")

"type | name=sy | 2565 | "
selenium.type("name=sy", "2565")

"click | name=ry |  | "
selenium.click("name=ry")

"type | name=ry | 2561 | "
selenium.type("name=ry", "2561")

"click | name=pass |  | "
selenium.click("name=pass")

"type | name=pass | Wasd@0659216799 | "
selenium.type("name=pass", "Wasd@0659216799")

"type | name=repass | Wasd@0659216799 | "
selenium.type("name=repass", "Wasd@0659216799")

"click | css=.custom-control-label |  | "
selenium.click("css=.custom-control-label")

"click | css=.btn-primary |  | "
selenium.click("css=.btn-primary")

"close |  |  | "
selenium.close()
